### ISSUE TITLE
Compile Module Files Adds All .ps1* Files Into Module

### ISSUE THREAD

**Issue by pauby** [psake/PowerShellBuild#13]
When running a build and specifying `$compileModule = $true` the build will fail as the `.ps1xml` file has been added into the module script.

## Expected Behavior
I expect only `*.ps1` files to be included in the module file.

## Current Behavior
Any files with extension `*.ps1*` are added into the module script.

## Possible Solution
The issue is in `Build-PSBuildModule.ps1` line 75:

```
$allScripts = Get-ChildItem -Path $Path -Filter *.ps1 -Recurse -ErrorAction SilentlyContinue
```

Removing the filter parameter and appending the filter onto the end of the path fixes it:

```
$allScripts = Get-ChildItem -Path (Join-Path -Path $Path -ChildPath '*.ps1') -Recurse -ErrorAction SilentlyContinue
```

Note that this only affects Windows PowerShell. PowerShell Core works with the `-filter` parameter correctly. Issue is discussed [here](https://stackoverflow.com/questions/12913734/powershell-get-childitem-filter-operates-differently-to-where-clause-with-same)

## Steps to Reproduce (for bugs)
1. Add `$compileModule = $true` into your build and make sure you have a `.ps1xml` file in your source folder / subfolders.
2. Run Invoke-Build

## Your Environment
* Module version used: 0.02
* Operating System and PowerShell version: Windows 10 and in both Windows PowerShell 5.1.17134.407 and PowerShell Core 6.1.1

**Comment by devblackops** [comment]
Fixed in #14
