### ISSUE TITLE
Discussion: Adding Headers & Footers To Module File / Functions

### ISSUE THREAD

**Issue by pauby** [psake/PowerShellBuild#15]
When I 'compile' my public and private functions into a script module I often have text at the top and bottom of the script module itself (`Set-StrictMode` and sometimes comments). It seems natural to therefore add a footer too.

And to take it one step further sometimes I do the same before and after function (that's not so common but just to take it that step further again).

Looking really to start a discussion around adding this in?

**Comment by devblackops** [comment]
Perhaps we take a look at taking a dependency on [ModuleBuilder](https://github.com/PoshCode/ModuleBuilder) to handle the logic of building/compiling the module?

**Comment by pauby** [comment]
I've used a fair number of Jaykul's modules - never heard of that one! Good choice.

**Comment by pauby** [comment]
Had a look at intergrating ModuleBuiler in. The issue around having to have a build.psd1 configuration file aside (this looks like a bug to me but there doesn't appear to be an issue raised so it could be me - I didn't work on it long enough) it will only do a module script suffix and prefix. It doesn't ao anything with the function prefix and suffix so it's not something that can be slotted in as a complete solution.

Will look at maybe pulling some of the code in and modifying it.
