### ISSUE TITLE
Importing module fails under Core on Linux

### ISSUE THREAD

**Issue by pauby** [psake/PowerShellBuild#22]
## Expected Behavior
When importing the module under Core on Linux it should work as it does under Windows. 

## Current Behavior
The module fails to load the public functions from the 'public' folder.

## Possible Solution
The folder is not called 'public' but 'Public'. Windows doesn't care about path case. Linux does.

## Steps to Reproduce (for bugs)
1. Under Core on Linux just import the module as normal.

## Your Environment
* Module version used: 0.3.0
* Operating System and PowerShell version: Ubuntu |PowerShell 6.1.2

**Comment by devblackops** [comment]
Fixed in #24
