### ISSUE TITLE
Status? eta wen :-)

### ISSUE THREAD

**Issue by bwright86** [psake/PowerShellBuild#3]
I had seen this module a while back and was curious where it stands today.

I have seen half a dozen different ways to templatize a CI/CD module, and was excited to see this attempt at building a standard template.

I currently use a mixture of a a few "Powershell Masters" to provide a decent CI/CD pipeline for my modules., but it still needs some additional rework to fully utilize all the tasks...

**Comment by devblackops** [comment]
@bwright86 I think this is complete enough to ship, although I will probably be shortening it to just `PowerShellBuild`. Have you tried it with version `4.8.0` of psake? I'd like to know if any issues are found.

**Comment by bwright86** [comment]
Wonderful, thank you for finalizing it. I will start playing with this soon, and will post any issues, if i find any.

**Comment by bwright86** [comment]
Taking an initial pass at integrating this with my CI plaster template. So far I like it, it is cleaner, there is good output, and it lessens the amount of static code sprinkled across modules.

I am currently using these values in my builds:
( I guess I am using a different structure for storing my module files)

properties {
    # These settings overwrite values supplied form the PowerShellBuild
    # module and govern how those tasks are executed
    $scriptAnalysisEnabled = $true

    $codeCoverageEnabled = $true
    $codeCoverageFiles = @(
        "$PSScriptRoot/<ModuleName>/Classes/*.ps1",
        "$PSScriptRoot/<ModuleName>/Private/*.ps1",
        "$PSScriptRoot/<ModuleName>/Public/*.ps1")

    $testRootDir = "$projectRoot/test"
}

**Comment by zloeber** [comment]
You may want to go through my own project to rip out code you like for this project. It's a fairly opinionated PowerShell Module building... er.. module with a customized version of plaster being used on the backend. I've used it in several projects and it can even import other modules as source functions for new projects. I maybe took things a bit too far noodling with it though. *shrug*[https://github.com/zloeber/ModuleBuild](https://github.com/zloeber/ModuleBuild)

**Comment by JustinGrote** [comment]
Hey @zloeber, I had a talk with @devblackops last night, there's lots of good areas to pull for general functions that can then be opinionated into plaster templates. I've got a similar opinionated template https://github.com/justingrote/PowerCD with all kinds of fancy stuff like automated versioning and it'd be great if we could get these into a common library rather than reinventing the wheel over and over.

**Comment by devblackops** [comment]
Indeed. It would be nice to consolidate into a common library for these tasks yet still provide enough flexibility for opinionated implementations. My opinionated Plaster template is [Stucco](https://github.com/devblackops/Stucco) but everyone can choose what they wish. The goal of this project is to provide that common task library.

**Comment by zloeber** [comment]
I started coding up a plugin system for adding module features dynamically (turn on/off nlog logging or dumb stuff like that) before my head imploded and I gave up :)
