### ISSUE TITLE
Add pester code coverage output parameters

### ISSUE THREAD

**Issue by solstone** [psake/PowerShellBuild#48]
## Expected Behavior
We should have 2 additional Preference parameters for the pester code coverage report output. 
CodeCoverageOutputFile
CodeCoverageOutputFileFormat

## Current Behavior
Currently the only Code coverage options are to enable it, files to be scanned and the failure threshold.  There are no options for output customization.

## Possible Solution
Add these to the PSBPreference object
$PSBPreference.Test.CodeCoverage.OutputFile
$PSBPreference.Test.CodeCoverage.OutputFileFormat

Then enabled those options in the Test-PSBuildPester.ps1 function

## Context
I am starting to learn to build modules in Azure Devops and I would like to be able to display the code coverage in the Azure pipeline report.  So far the only way I have found to do that is to have pester output the code coverage report to a JaCoCo xml file.

## Your Environment
Windows 10 2004
Powershell 5.1
BuildHelpers     = '2.0.15'
psake            = '4.9.0'
PSScriptAnalyzer = '1.19.1'
PowerShellBuild  = '0.4.0'

**Comment by devblackops** [comment]
Implemented in https://github.com/psake/PowerShellBuild/commit/638b8378322aa8a50318b95fde9c01700fc64763
