### ISSUE TITLE
Provide property for internal repository publishing

### ISSUE THREAD

**Issue by bwright86** [psake/PowerShellBuild#5]
## Expected Behavior
1. Provide an alternate value for a PublishGallery or Repository.
2. During the Publish step, the module is packaged and published to the chosen repository

## Current Behavior
No value for specifying an alternate repository (i.e. an Internal repository.)

## Possible Solution
Add a property name that allows a repository name to be provided. Either through BuildHelpers or in PowershellBuild

## Steps to Reproduce (for bugs)
N/A

## Context
I am looking to integrate this module in my current CI/CD pipeline, and I currently publish to an internal repository at work.

## Your Environment

* Module version used: PowershellBuild 0.1.1
* Operating System and PowerShell version: Windows 10 Pro, Powershell 5.1.17134.228

**Comment by bwright86** [comment]
Whoops, just realized there isn't a task for Publish.

Would it be difficult to add a Publish task to this module?
It really just calls Publish-Module under the hood, but would require some additional properties be added.

**Comment by devblackops** [comment]
Yep. Working on adding the `Publish` task now!

**Comment by devblackops** [comment]
Fixed in f638e7def7b962bc7b0d00dccf06cdd2d813d53f

**Comment by bwright86** [comment]
LGTM

Except the Publish function looks like the ‘-WhatIf’ switch is permanently set to ‘$True’

Was that just for testing things?

**Comment by bwright86** [comment]
nvm, looks like in a future commit you removed it (4b399cf)

I was able to build and publish a module to an internal repository w/ relative ease :-)

Thank you for adding this.
