### ISSUE TITLE
should configuration.Run.PassThru  be set to true?

### ISSUE THREAD

**Issue by pearcec** [psake/PowerShellBuild#51]
https://github.com/psake/PowerShellBuild/blob/b1efdb76bcbb2a0a43210d8b534ca1c94c9ae5b7/PowerShellBuild/Public/Test-PSBuildPester.ps1#L80

If this is set to $false, then no results are return 

https://github.com/psake/PowerShellBuild/blob/b1efdb76bcbb2a0a43210d8b534ca1c94c9ae5b7/PowerShellBuild/Public/Test-PSBuildPester.ps1#L94

And it will always be successful. For example:

https://github.com/pearcec/Invoke-Terraform/runs/2313617121?check_suite_focus=true#step:3:202

**Comment by webtroter** [comment]
I just ran into that too.

My tests fails but the Publish Task still run.

**Comment by webtroter** [comment]
https://github.com/psake/PowerShellBuild/commit/10c90512a3ed3f08081e84130d1c6cbfca1232ca#diff-02fdd73924b0554973b2bcc296d22242dce416c5b4655def926f0cc61dbfa7db

Found where it came from. I'll do a PR I guess.

**Comment by devblackops** [comment]
@webtroter Thanks for catching that!
