### ISSUE TITLE
Discussion: Settings as Hashtable Variable?

### ISSUE THREAD

**Issue by JustinGrote** [psake/PowerShellBuild#6]
This would be more of a usability discussion, but some variables like $outDir are pretty generic and may conflict with user build scripts who aren't aware of them or are porting them out.

Should these settings maybe be in something like $PSBPreference as a hashtable, so you could set them like:

$PSBPreference.OutDir = "MyCustomDir"
$PSBPreference

Plus as a hashtable they could also be defined in a .psd1 file and imported if someone had a preference for that vs. defining in build script directly.

This would also make them more discoverable since they could be populated from the beginning with defaults and easily referenced. The tradeoff is obviously more typing and maybe less intuitive to new users, but the BuildHelpers variables aren't that much less intuitive either and noone seems to have issue with those.

A class is also an option, but the only benefit gained there would be maybe adding Validate for parameters that have limited options (booleans, validatesets, and whatnot), and classes are hard to expose, probably unnecessary

Thoughts? I'd be willing to PR the refactor if people agree this is the better way to go.

**Comment by devblackops** [comment]
I like it for organization purposes but I think we may run into an issue. In psake, I changed the way the `properties` block is applied. It is now held in a stack so the common task module could define behavior via property variables and calling psake scripts can override these because of the order in which they are executed. If we store these settings in a hashtable the user could inadvertently wipe the entire hashtable by calling this:

```powershell
$PSBPreference = @{
    OutDir = 'MyCustomDir'
}
```

instead of this:

```powershell
$PSBPreference.OutDir = 'MyCustomDir'
```

**Comment by JustinGrote** [comment]
Well there's nothing stopping them from setting $Outdir =
$PSBPreference.outdir if that's their preference, only problem is they will
fall out of sync that way.

I don't know if it's possible to set up special "pointer" variables, e.g.
with an option setting,  $PSBPreference.outdir also gets exposed as
$Outdir, but both point to the same variable reference, so if you update
one you update the other, that would allow for that "easier" case.

Other option is just do what buildhelpers does and save them in $env with a
PSB prefix...

**Comment by devblackops** [comment]
@JustinGrote I've refactored the build properties into a single readonly hashtable. I still need to fully test but this looks like it will work.

Docs with new property names:
https://github.com/psake/PowerShellBuild#task-customization

**Comment by pauby** [comment]
> If we store these settings in a hashtable the user could inadvertently wipe the entire hashtable by calling this:

Is that really a concern? We're dealing with technical people. If they do that to the hashtable then they are going to have other issues too. That's also really a _PowerShell understanding how hashtables work_ than a PowerShellBuild one?

**Comment by JustinGrote** [comment]
@pauby, I think the intent is to prevent unintentional accidents that are difficult to troubleshoot, especially if the implementation is easy as in this case. It's a laudable goal, even us professionals do dumb stuff too :)

The Invoke-Build conversion script I wrote should bring that hashtable over as-is, and all the references match, so failing a weird scope bug, yeah it should work with Invoke-Build just fine.

**Comment by devblackops** [comment]
I will release it as `0.3.0-beta`. This will technically be a breaking change but we are still at `v0.x` and there is a note in the [README](https://github.com/psake/PowerShellBuild/blob/master/README.md#status---work-in-progress) that this project is still a work in progress.

**Comment by devblackops** [comment]
`0.3.0-beta` has been published to PSGallery.
