### ISSUE TITLE
Task StageFile throws an error "no param 'ModuleManifestPath' "

### ISSUE THREAD

**Issue by webtroter** [psake/PowerShellBuild#8]
Calling the task "StageFile" throws "ERROR: A parameter cannot be found that matches parameter name 'ModuleManifestPath'."

## Expected Behavior
I expect the build to be successful.

## Current Behavior
The build fails because the task "StageFile" calls Build-PSBuildModule with a param ModuleManifestPath that it doesn't support.

## Possible Solution
Adding a ModuleManifestPath to
or
Removing the Line ModuleManifestPath from the hashtable

## Steps to Reproduce (for bugs)
I converted a existing project to use PSBuild, by copy paste. I'm pretty sure it is easy to reproduce with a simple blank module. 

## Your Environment
* Module version used:
* Operating System and PowerShell version: Windows 10 1803, PS 5.1.17134.228

**Comment by devblackops** [comment]
@webtroter What version are you using? This should already be fixed in `0.1.1`.

**Comment by webtroter** [comment]
Weird.... I simply added some Stucco files to my project, and ran the build...

Aahhhh, I see now. requirements.psd1 specifies 0.1.0

After updating, I now get a 0.2.0. Yeay! Lets see if it works better

**Comment by devblackops** [comment]
I think that was a bug in the `0.1.0` release.
